<a href="https://colab.research.google.com/github/Rushikesh419/Machine-learning/blob/main/ridge_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df1=pd.read_csv('/content/drive/MyDrive/Advertising.csv')

In [11]:
df1

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [12]:
df=df1.drop('Unnamed: 0',axis=1)

In [13]:
X=df.drop('Sales',axis=1)

In [14]:
y=df['Sales']

In [15]:
from sklearn.preprocessing import PolynomialFeatures

In [16]:
polynomial_converter=PolynomialFeatures(degree=3,include_bias=False)

In [17]:
poly_feature=polynomial_converter.fit_transform(X)

In [18]:
poly_feature.shape

(200, 19)

In [19]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test=train_test_split(poly_feature,y,test_size=0.3,random_state=101)

In [26]:
X_train.shape

(140, 19)

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
scalar=StandardScaler()

In [29]:
scalar.fit(X_train)

StandardScaler()

In [30]:
X_train=scalar.transform(X_train)

In [31]:
X_test=scalar.transform(X_test)

In [32]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [34]:
from sklearn.linear_model import Ridge

In [36]:
ridge_model=Ridge(alpha=10)

In [37]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [38]:
test_pred=ridge_model.predict(X_test)

In [39]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [40]:
MAE=mean_absolute_error(y_test,test_pred)

In [41]:
MAE

0.5774404204714163

In [42]:
RMSE=np.sqrt(mean_squared_error(y_test,test_pred))

In [43]:
RMSE

0.894638646131965

In [ ]:
# for using a better alpha use a cross validation

In [44]:
from sklearn.linear_model import RidgeCV
# RidgeCV perform cross validation for variety of alpha value then its report back best alpha value
#  and going to get ave error matrics for all

In [55]:
# scoring metrics availabe
from sklearn.metrics import SCORERS

In [56]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weig

In [52]:
ridge_CV_model=RidgeCV(alphas=(0.1,1,10),scoring='neg_mean_absolute_error')

In [53]:
ridge_CV_model.fit(X_train,y_train)

RidgeCV(alphas=(0.1, 1, 10), scoring='neg_mean_absolute_error')

In [54]:
# best performing alpha
ridge_CV_model.alpha_

0.1

In [57]:
# check performance
test_pred=ridge_CV_model.predict(X_test)

In [59]:
MAE=mean_absolute_error(y_test,test_pred)
RMSE=np.sqrt(mean_squared_error(y_test,test_pred))

In [61]:
MAE

0.427377488434534

In [62]:
RMSE

0.6180719926938822

In [63]:
ridge_CV_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])